# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='likes',
            new_name='rewards',
        ),
    ]
