# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 11:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoke', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_of_collection',
            field=models.DateField(default=datetime.date(2017, 12, 20)),
        ),
    ]
