# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoke', '0007_auto_20171220_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
