# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecoke', '0010_auto_20180119_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_of_collection',
            field=models.DateField(default=datetime.date(2018, 1, 20)),
        ),
    ]
