# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoke', '0011_auto_20180120_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_of_collection',
            field=models.DateField(default=datetime.date(2018, 1, 23)),
        ),
    ]
