# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoke', '0013_auto_20180124_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_of_collection',
            field=models.DateField(default=datetime.date(2018, 1, 25)),
        ),
    ]
